### ISSUE TITLE
Debian 12 bookworm packages

### ISSUE THREAD

**Issue by sblaisot** [OCSInventory-NG/packages#6]
Hi,

Debian 12 Bookworm has been released since 2023-06-10. However, packages for Debian 12 Bookworm are not yet available at http://deb.ocsinventory-ng.org/debian/dists/

Do you plan to release packages for Debian 12 Bookworm and do you have an ETA?

**Comment by gillesdubois** [comment]
Hi,

We are going to add bookworm soon.

Thanks for your feedback :) 

Regards,
Gilles DUBOIS.

**Comment by sblaisot** [comment]
hi @gillesdubois 

Any news?

Debian 12 bookworm has been out for 6 month now.

**Comment by gillesdubois** [comment]
Hi,

Publishing went wrong, should be good now.
Thanks for your remainder ! 

Regards,
Gilles DUBOIS.

**Comment by sblaisot** [comment]
I can confirm packages install correctly on debian 12 bookworm.

Thanks @gillesdubois 

Closing this issue now.
